// src/constants/maintainers.ts

export const MAINTAINERS = new Set<string>([
  "07calc",
  "joYBoY1210",
  "Pratikrkcha",
  "BluesIsekai",
  "23abdul23",
  "Washiki",
  "Shravanimath",
  "VaidikKindaCodes",
  "MishtiGarg250",
  "Aryan9059",
  "adith-nr",
  "AnandMayank",
  "sankalpj47",
  "Suvanwita",
  "Surya-Raghuram",
  "Paraspandey-debugs",
  "angrycrax",
  "Dheeraj-06",
  "aadyagupta23",
  "Aryan-coder06",
  "SaqlainSQX",
  "HGRgamer",
  "vichanshu",
  "Scorchedpearl",
  "yash194",
  "sahilgupta2006",
  "Zonedoutdg",
  "Rational-Idiot",
  "bitflipper19",
  "ShubhamKumarSahu-svg",
  "Soham-Donode",
  "Vinesh-27",
  "shrmaanubhav",
  "krichyrich",
  "kyanmahajan",
  "ShonWaghchoure",
  "Jazzrahi",
  "Goddbott",
]);

export const isMaintainer = (githubId: string) =>
  MAINTAINERS.has(githubId);
